build(Makefile): compile protocol as shared library and use same Makefile architecture across all of the project.

diff --git a/libs/protocol/Makefile b/libs/protocol/Makefile
--- a/libs/protocol/Makefile
+++ b/libs/protocol/Makefile
@@ -1,89 +1,149 @@
 ##
 ## EPITECH PROJECT, 2024
-## Arcade
+## my_teams
 ## File description:
 ## Makefile
 ##
 
-include Makefile_colors.mk
+NAME		:=	libmyprotocol.so
+EXT			:=	.c
 
-LIB 		= libmyprotocol.a
-CC 			= gcc
+DIR			:=	src
+SRC			:=	$(addprefix $(DIR)/,								\
+					p_create_payload.c								\
+				)
 
-VPATH 		:= ./src
-VPATH 		+= ./src/client
-VPATH 		+= ./src/server
-VPATH 		+= ./src/server/utils
+DIR			+=	src/client
+SRC			+=	$(addprefix $(lastword $(DIR))/,					\
+					p_client_close.c								\
+					p_client_create.c								\
+					p_client_listen.c								\
+					p_client_send_packet.c							\
+				)
 
-vpath %.c $(VPATH)
+DIR			+=	src/server
+SRC			+=	$(addprefix $(lastword $(DIR))/,					\
+					p_server_close.c								\
+					p_server_create.c								\
+					p_server_listen.c								\
+					p_server_send_packet.c							\
+				)
 
-SRC 		:= p_client_create.c
-SRC 		+= p_client_listen.c
-SRC 		+= p_server_create.c
-SRC 		+= p_server_listen.c
-SRC 		+= p_client_send_packet.c
-SRC 		+= p_server_send_packet.c
-SRC 		+= p_create_payload.c
-SRC 		+= new_client.c
-SRC			+= select_server.c
-SRC			+= server_bind.c
-SRC			+= server_listen.c
-SRC			+= server_setsockopt.c
-SRC			+= server_socket.c
-SRC			+= get_client.c
-SRC			+= p_server_close.c
-SRC			+= p_client_close.c
+DIR			+=	src/server/utils
+SRC			+=	$(addprefix $(lastword $(DIR))/,					\
+					get_client.c									\
+					new_client.c									\
+					select_server.c									\
+					server_bind.c									\
+					server_listen.c									\
+					server_setsockopt.c								\
+					server_socket.c									\
+				)
 
-BUILD_DIR 	= build
-OBJ 		:= $(SRC:%.c=$(BUILD_DIR)/%.o)
+FU_DIR		:=	tests/func
 
-CFLAGS 		:= -iquote./include -iquote../../include
-CFLAGS		+= -Wall -Wextra -DSMCLN=;
-AR			= ar
+UT_DIR		:=	tests/unit
+UT_SRC		:=	$(filter-out src/main.c, $(SRC))
+UT_SRC		+=	$(addprefix $(UT_DIR)/,								\
+				)
 
-DIE         = exit 1
-ECHO        = echo -e
+DIR_BUILD	:=	build
+DIR_BIN		:=	$(DIR_BUILD)/bin
 
-%.c:
-	@ $(ECHO) "${_B_RED}[ERROR]${_END} File ${_B_WHITE}$@${_END} not found."
-	@ $(ECHO) "${_B_RED}===============> $(LIB) <================${_END}\n\n"
-	@ $(DIE)
+DIR_OBJ		:=	$(DIR_BUILD)/obj
+OBJ			:=	$(patsubst %$(EXT),$(DIR_OBJ)/%.o,$(SRC))
+DEP			:=	$(OBJ:.o=.d)
 
-all: $(LIB)
-	@ $(ECHO) "${_B_GREEN}[OK]${_END} Compilation of ${_B_WHITE}$(LIB)${_END} \
-	done."
-	@ $(ECHO) "${_B_GREEN}===============> $(LIB) <================${_END}\n\n"
+UT_DIR_OBJ	:=	$(DIR_BUILD)/tests/unit
+UT_OBJ		:=	$(patsubst %$(EXT),$(UT_DIR_OBJ)/%.o,$(UT_SRC))
+UT_DEP		:=	$(UT_OBJ:.o=.d)
 
-$(BUILD_DIR)/%.o: %.c
-	@ mkdir -p $(@D)
-	@ $(CC) $(LIBFLAGS) -c $< -o $@ $(CFLAGS)
-	@ $(ECHO) "${_CYAN}[OK]$(_END)	-> $(CC)    $(_U_WHITE)$<$(_END)"
+DG_DIR_OBJ	:=	$(DIR_BUILD)/debug
+DG_OBJ		:=	$(patsubst %$(EXT),$(DG_DIR_OBJ)/%.o,$(SRC))
+DG_DEP		:=	$(DG_OBJ:.o=.d)
 
-$(LIB): $(OBJ) $(SRC)
-	@ mkdir -p $(BUILD_DIR)
-	@ $(AR) rc $(LIB) $(OBJ)
-	@ $(ECHO) "${_CYAN}[OK]$(_END)	-> $(AR)    $(_U_WHITE)$@$(_END)"
-	@ $(ECHO) "$(_B_PURPLE)[STATS]$(_END)	-> \
-	$(shell echo "$?" | wc -w) file(s) compiled${_END}."
+DEBUG		:=	$(DIR_BIN)/debug
+FU_TEST		:=	$(FU_DIR)/tester.sh
+UT_TEST		:=	$(DIR_BIN)/unit_test
 
-debug: CFLAGS += -DDEBUG -g
+RM			:=	rm -rf
+
+CC			:=	gcc
+CFLAGS		:=	-iquote./include -iquote../../include				\
+				-Wall -Wextra
+LDFLAGS		:=
+
+all:				$(NAME)
+
+define CREATE_DIR
+	@if [ ! -d $(dir $@) ]; then									\
+		mkdir -p $(dir $@) 											\
+		&& printf "\033[93m[CREATED]\033[0m %s\n" $(dir $@)			\
+		|| printf "\033[31m[ERROR]\033[0m %s\n"   $(dir $@);		\
+	fi
+endef
+
+define BUILD_OBJ
+	@$(RM) $(patsubst %.o,%.gcda,$@)
+	@$(RM) $(patsubst %.o,%.gcno,$@)
+	$(CREATE_DIR)
+	@$(CC) $(CFLAGS) -MMD -c $< -o $@								\
+	&& printf "\033[32m[OK]\033[0m %s\n" $<							\
+	|| printf "\033[31m[KO]\033[0m %s\n" $<
+endef
+
+$(DIR_OBJ)/%.o:		%$(EXT); $(BUILD_OBJ)
+$(UT_DIR_OBJ)/%.o:	%$(EXT); $(BUILD_OBJ)
+$(DG_DIR_OBJ)/%.o:	%$(EXT); $(BUILD_OBJ)
+
+define COMPILE
+	$(CREATE_DIR)
+	@$(CC) -o $@ $^ $(LDFLAGS)			 							\
+	&& printf "\033[32m[SUCCES]\033[0m %s\n" $@						\
+	|| printf "\033[31m[ERROR]\033[0m %s\n"  $@
+endef
+
+define COMPILE_LIB
+	$(CREATE_DIR)
+	@$(CC) --shared -o $@ $^										\
+	&& printf "\033[32m[SUCCES]\033[0m %s\n" $@						\
+	|| printf "\033[31m[ERROR]\033[0m %s\n"  $@
+endef
+
+-include $(DEP)
+$(NAME):			$(OBJ); 	$(COMPILE_LIB)
+
+tests_functional:	$(FU_TEST) $(NAME)
+	@$^
+
+-include $(UT_DEP)
+$(UT_TEST):			LDFLAGS += -lcriterion --coverage
+$(UT_TEST):			$(UT_OBJ);	$(COMPILE)
+tests_unit:			$(UT_TEST)
+	@cp $(UT_TEST) $(UT_DIR_OBJ)
+	@$(UT_DIR_OBJ)/$(notdir $<)
+
+-include $(DG_DEP)
+$(DEBUG):			CFLAGS += -g -DDEBUG
+$(DEBUG):			$(DG_OBJ); 	$(COMPILE_LIB)
+debug:				$(DEBUG)
+
+tests_run:			tests_functional tests_unit
+	gcovr $(UT_DIR_OBJ) --exclude tests/
+	gcovr $(UT_DIR_OBJ) --exclude tests/ --branches
 
 clean:
-	@ $(RM) *.gcda
-	@ $(RM) *.gcno
-	@ $(RM) *.gcov
-	@ $(RM) vgcore.*
-	@ $(RM) -rf $(BUILD_DIR)
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	*.gcda${_END}"
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	*.gcno${_END}"
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	*.gcov${_END}"
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	vgcore.*${_END}"
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	$(BUILD_DIR)${_END}"
+	@[ -d $(DIR_BUILD) ]											\
+	&& $(RM) $(DIR_BUILD)											\
+	&& printf "\033[31m[DELETED]\033[0m %s\n" $(DIR_BUILD) || true
 
-fclean: clean
-	@ $(RM) $(LIB)
-	@ $(ECHO) "${_BLACK}${_BB_WHITE}-> $(RM)	$(LIB)${_END}"
+fclean:				clean
+	@[ -f $(NAME) ]													\
+	&& $(RM) $(NAME)												\
+	&& printf "\033[31m[DELETED]\033[0m %s\n" $(NAME) || true
 
-re: fclean all
+re:					fclean all
 
-.PHONY: all clean fclean re
+.PHONY:				all tests tests_run debug clean fclean re doc
+
+.SILENT:			all tests tests_run debug clean fclean re doc
